// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FSM
{
	public enum PlayerState
	{
		Idle,
		Run,
		Jump
	}
	
	public class ChildFSM : BaseFSM<PlayerState>
	{
		public ChildFSM () : base()
		{			
			this.currentState = PlayerState.Idle;
			//Define the state machine transitions
			this.transitions = new Dictionary<StateTransition, PlayerState>
			{
				{ new StateTransition(PlayerState.Idle, PlayerState.Run), PlayerState.Run }, //From Idle state to Run state 
				{ new StateTransition(PlayerState.Run, PlayerState.Jump), PlayerState.Jump }, 
			};	
		}
		
	}
}

