// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace FSM
{
	public class Program
	{
		static void Main(string[] args)
		{
			ChildFSM fsm = new ChildFSM();
			Console.WriteLine("Current State = " + fsm.currentState);
			Console.WriteLine("Command.Begin: Current State = " + fsm.MoveNext(PlayerState.Run));
			Console.WriteLine("Invalid transition: " + fsm.CanReachNext(PlayerState.Idle));
			Console.WriteLine("Previous State = " + fsm.previusState);
		}
	}

}


